import { Permission } from './permissions';
import { Role, ROLES } from './roles';

export const PERMISSION_MATRIX: Record<Role, Permission[]> = {
  [ROLES.PLATFORM_ADMIN]: [
    Permission.TENANT_CREATE,
    Permission.TENANT_UPDATE,
    Permission.TENANT_DELETE,
    Permission.TENANT_VIEW,
    Permission.USER_CREATE,
    Permission.USER_UPDATE,
    Permission.USER_DELETE,
    Permission.USER_VIEW,
    Permission.PROJECT_CREATE,
    Permission.PROJECT_UPDATE,
    Permission.PROJECT_DELETE,
    Permission.PROJECT_VIEW,
    Permission.CLIENT_CREATE,
    Permission.CLIENT_UPDATE,
    Permission.CLIENT_DELETE,
    Permission.CLIENT_VIEW,
    Permission.TICKET_CREATE,
    Permission.TICKET_UPDATE,
    Permission.TICKET_DELETE,
    Permission.TICKET_VIEW,
    Permission.TICKET_ASSIGN,
    Permission.VIEW_AUDIT_LOGS,
    Permission.VIEW_REPORTS,
    Permission.MANAGE_SETTINGS,
  ],
  [ROLES.TENANT_ADMIN]: [
    Permission.TENANT_VIEW,
    Permission.TENANT_UPDATE, // Can update their own tenant details
    Permission.USER_CREATE,
    Permission.USER_UPDATE,
    Permission.USER_DELETE,
    Permission.USER_VIEW,
    Permission.PROJECT_CREATE,
    Permission.PROJECT_UPDATE,
    Permission.PROJECT_DELETE,
    Permission.PROJECT_VIEW,
    Permission.CLIENT_CREATE,
    Permission.CLIENT_UPDATE,
    Permission.CLIENT_DELETE,
    Permission.CLIENT_VIEW,
    Permission.TICKET_CREATE,
    Permission.TICKET_UPDATE,
    Permission.TICKET_DELETE,
    Permission.TICKET_VIEW,
    Permission.TICKET_ASSIGN,
    Permission.VIEW_REPORTS,
  ],
  [ROLES.ENGINEER]: [
    Permission.TENANT_VIEW,
    Permission.USER_VIEW,
    Permission.PROJECT_VIEW,
    Permission.CLIENT_VIEW,
    Permission.TICKET_CREATE,
    Permission.TICKET_UPDATE,
    Permission.TICKET_VIEW,
  ],
};
