export const Permission = {
  // Tenant operations
  TENANT_CREATE: 'TENANT_CREATE',
  TENANT_UPDATE: 'TENANT_UPDATE',
  TENANT_DELETE: 'TENANT_DELETE',
  TENANT_VIEW: 'TENANT_VIEW',

  // User operations
  USER_CREATE: 'USER_CREATE',
  USER_UPDATE: 'USER_UPDATE',
  USER_DELETE: 'USER_DELETE',
  USER_VIEW: 'USER_VIEW',

  // Project operations
  PROJECT_CREATE: 'PROJECT_CREATE',
  PROJECT_UPDATE: 'PROJECT_UPDATE',
  PROJECT_DELETE: 'PROJECT_DELETE',
  PROJECT_VIEW: 'PROJECT_VIEW',

  // Client operations
  CLIENT_CREATE: 'CLIENT_CREATE',
  CLIENT_UPDATE: 'CLIENT_UPDATE',
  CLIENT_DELETE: 'CLIENT_DELETE',
  CLIENT_VIEW: 'CLIENT_VIEW',

  // Ticket operations
  TICKET_CREATE: 'TICKET_CREATE',
  TICKET_UPDATE: 'TICKET_UPDATE',
  TICKET_DELETE: 'TICKET_DELETE',
  TICKET_VIEW: 'TICKET_VIEW',
  TICKET_ASSIGN: 'TICKET_ASSIGN',

  // System operations
  VIEW_AUDIT_LOGS: 'VIEW_AUDIT_LOGS',
  VIEW_REPORTS: 'VIEW_REPORTS',
  MANAGE_SETTINGS: 'MANAGE_SETTINGS',
} as const;

export type Permission = (typeof Permission)[keyof typeof Permission];
